name: CI

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: finwo/dep@edge
      - run : dep install
      - run : make clean
      - run : make
      - run : ./test
